 .bashrc# 
 Source global definitionsif 
 [ -f /etc/bashrc ]; then        
      ./usr/local/bin
      fi
      
      # Uncomment the following line if you don't like systemctl's auto-paging feature:
      # export SYSTEMD_PAGER=
      
      # User specific aliases and functions
